local Cmp = {
		CmpItemAbbrDeprecated = {fg = C.gray, style = "strikethrough", },
		CmpItemAbbrMatch = {fg = C.ui3_blue, },
		CmpItemAbbrMatchFuzzy = {fg = C.ui3_blue, },
		CmpItemKindFunction = {fg = C.purple, },
		CmpItemKindMethod = {fg = C.purple, },
		CmpItemKindConstructor = {fg = C.cyan, },
		CmpItemKindClass = {fg = C.cyan, },
		CmpItemKindInterface = {fg = C.cyan, },
		CmpItemKindEnum = {fg = C.cyan, },
		CmpItemKindStruct = {fg = C.cyan, },
		CmpItemKindEvent = {fg = C.purple, },
		CmpItemKindVariable = {fg = C.light_blue, },
		CmpItemKindField = {fg = C.light_blue, },
		CmpItemKindProperty = {fg = C.light_blue, },
		CmpItemKindEnumMember = {fg = C.light_blue, },
		CmpItemKindKeyword = {fg = C.yellow_orange, },
		CmpItemKindConstant = {fg = C.blue, },
		CmpItemKindValue = {fg = C.fg, },
		CmpItemKindUnit = {fg = C.fg, },
		CmpItemKindText = {fg = C.fg, },
		CmpItemKindSnippet = {fg = C.fg, },
		CmpItemKindFile = {fg = C.fg, },
		CmpItemKindFolder = {fg = C.fg, },
		CmpItemKindColor = {fg = C.fg, },
		CmpItemKindReference = {fg = C.fg, },
		CmpItemKindOperator = {fg = C.fg, },
		CmpItemKindTypeParameter = {fg = C.fg, },
}

return Cmp