local Misc = {
		diffAdded = {fg = C.sign_add, },
		diffRemoved = {fg = C.sign_delete, },
		diffFileId = {fg = C.blue, style = "bold,reverse", },
		diffFile = {fg = C.alt_bg, },
		diffNewFile = {fg = C.green, },
		diffOldFile = {fg = C.red, },
		debugPc = {bg = C.cyan, },
		debugBreakpoint = {fg = C.red, style = "reverse", },
		CodiVirtualText = {fg = C.hint_blue, },
		CompeDocumentation = {bg = C.alt_bg, },
		xmlTag = {fg = C.cyan, },
		xmlTagName = {fg = C.cyan, },
		xmlEndTag = {fg = C.cyan, },
		yamlPlainScalar = {fg = C.orange, },
		yamlTSField = {fg = C.blue, },
		luaFunc = {fg = C.yellow, },
		luaFunction = {fg = C.blue, },
		htmlH1 = {fg = C.fg, },
		htmlH2 = {fg = C.fg, },
		htmlH3 = {fg = C.fg, },
		htmlH4 = {fg = C.fg, },
		htmlH5 = {fg = C.fg, },
		htmlH6 = {fg = C.fg, },
		cssBraces = {fg = C.fg, },
		cssInclude = {fg = C.purple, },
		cssTagName = {fg = C.yellow_orange, },
		cssClassName = {fg = C.yellow_orange, },
		cssPseudoClass = {fg = C.yellow_orange, },
		cssPseudoClassId = {fg = C.yellow_orange, },
		cssPseudoClassLang = {fg = C.yellow_orange, },
		cssIdentifier = {fg = C.yellow_orange, },
		cssProp = {fg = C.light_blue, },
		cssDefinition = {fg = C.light_blue, },
		cssAttr = {fg = C.orange, },
		cssAttrRegion = {fg = C.orange, },
		cssColor = {fg = C.orange, },
		cssFunction = {fg = C.purple, },
		cssFunctionName = {fg = C.light_green, },
		cssVendor = {fg = C.orange, },
		cssValueNumber = {fg = C.light_green, },
		cssValueLength = {fg = C.light_green, },
		cssUnitDecorators = {fg = C.light_green, },
		cssStyle = {fg = C.light_blue, },
		cssImportant = {fg = C.blue, },
}

return Misc