local Misc = {
		diffAdded = {fg = C.sign_add, },
		diffRemoved = {fg = C.sign_delete, },
		diffFileId = {fg = C.blue, style = "bold,reverse", },
		diffFile = {fg = C.alt_bg, },
		diffNewFile = {fg = C.green, },
		diffOldFile = {fg = C.red, },
		debugPc = {bg = C.cyan, },
		debugBreakpoint = {fg = C.red, style = "reverse", },
		CodiVirtualText = {fg = C.hint_blue, },
		CompeDocumentation = {bg = C.alt_bg, },
		xmlTag = {fg = C.cyan, },
		xmlTagName = {fg = C.cyan, },
		xmlEndTag = {fg = C.cyan, },
		yamlPlainScalar = {fg = C.orange, },
		yamlTSField = {fg = C.blue, },
		luaFunc = {fg = C.yellow, },
		luaFunction = {fg = C.blue, },
		htmlH1 = {fg = C.fg, },
		htmlH2 = {fg = C.fg, },
		htmlH3 = {fg = C.fg, },
		htmlH4 = {fg = C.fg, },
		htmlH5 = {fg = C.fg, },
		htmlH6 = {fg = C.fg, },
}

return Misc